

DEFAULT_IMAGE_URLS = (
    "http://images.cocodataset.org/val2017/000000000285.jpg",
    "http://images.cocodataset.org/val2017/000000000632.jpg",
    "http://images.cocodataset.org/val2017/000000000724.jpg",
    "http://images.cocodataset.org/val2017/000000000776.jpg",
    "http://images.cocodataset.org/val2017/000000001000.jpg",
    "http://images.cocodataset.org/val2017/000000001268.jpg",
    "http://images.cocodataset.org/val2017/000000006012.jpg",
    "http://images.cocodataset.org/val2017/000000190236.jpg",
    "http://images.cocodataset.org/val2017/000000331352.jpg",
    "http://images.cocodataset.org/val2017/000000517069.jpg",
)


# Test prompts for multimodal generation (10 prompts matching the 10 images)
# Each prompt expects a one-word answer
MULTIMODAL_GENERATION_PROMPTS = (
    "What animal is in the picture? Answer with one word.",  # Expected: bear
    "Was the image taken indoors or outdoors? Answer with indoors or outdoors.",  # Expected: indoors
    "Was the image taken outdoors? Answer with yes or no.",  # Expected: yes
    "How many bears in the picture? Answer with one word.",  # Expected: 3
    "Was the image taken outdoors? Answer with yes or no.",  # Expected: yes
    "Was the image taken indoors or outdoors? Answer with indoors or outdoors.",  # Expected: outdoors
    "How many kinds of fruits are in the picture? Answer with one word.",  # Expected: 2
    "Was the image taken indoors or outdoors? Answer with indoors or outdoors.",  # Expected: indoors
    "Was the image taken indoors or outdoors? Answer with indoors or outdoors.",  # Expected: indoors
    "What's the color of the building? Answer with one word.",  # Expected: white
)


# Test prompts for multimodal embedding (10 prompts matching the 10 images)
# Comments indicate expected relevance score (高分=high score, 低分=low score)
MULTIMODAL_EMBEDDING_TEXTS = (
    "A bear in the image",  # 高分
    "An outdoor scene",  # 低分
    "An outdoor setting",  # 高分
    "Multiple bears",  # 高分
    "An outdoor environment",  # 高分
    "An outdoor location",  # 高分
    "Bananas or fruits",  # 高分
    "An outdoor view",  # 低分
    "An outdoor scene",  # 低分
    "An outdoor setting",  # 高分
)


# Test prompts for multimodal reranking (10 prompts matching the 10 images)
# Comments indicate expected relevance score (高分=high score, 低分=low score)
MULTIMODAL_RERANKING_QUERIES = (
    "A bear in the image",  # 高分
    "An outdoor scene",  # 低分
    "An outdoor setting",  # 高分
    "Multiple bears",  # 高分
    "An outdoor environment",  # 高分
    "An outdoor location",  # 高分
    "Bananas or fruits",  # 高分
    "An outdoor view",  # 低分
    "An outdoor scene",  # 低分
    "An outdoor setting",  # 高分
)


# Test prompts for text embedding (base texts)
TEXT_EMBEDDING_TEXTS = (
    "What is the capital of China?",
    "Explain gravity",
    "The capital of China is Beijing.",
    "Gravity is a force that attracts two bodies.",
    "Machine learning is a subset of AI.",
    "Python is a programming language.",
)

# Additional texts for expanding batch size in embedding tests
TEXT_EMBEDDING_VARIATIONS = (
    "What is artificial intelligence?",
    "Explain quantum physics",
    "What is deep learning?",
    "Explain neural networks",
    "What is natural language processing?",
    "Explain computer vision",
)

# Test prompts for text reranking (queries)
TEXT_RERANKING_QUERIES = (
    "What is the capital of China?",
    "Explain gravity",
    "What is machine learning?",
    "Who wrote 'Romeo and Juliet'?",
    "What is the chemical formula for water?",
    "What is the highest mountain in the world?",
    "What is photosynthesis?",
    "When did World War II end?",
    "What is the largest planet in our solar system?",
    "What is the currency of Japan?",
    "Who painted the Mona Lisa?",
    "What is the capital of Japan?",
    "What is the powerhouse of the cell?",
    "What year did the Titanic sink?",
    "What is the chemical symbol for gold?",
    "Who wrote the Harry Potter series?",
    "What is the largest desert in the world?",
    "What is the speed of light?",
    "What is the currency of the United Kingdom?",
    "Who was the first person to walk on the moon?",
    "What is the main ingredient in guacamole?",
    "In what year did the first World War begin?",
    "What is the capital of Australia?",
    "What is the hardest known natural material?",
    "Who discovered penicillin?",
    "What is the longest river in the world?",
    "What is the primary language spoken in Brazil?",
    "Who painted 'Starry Night'?",
    "What is the smallest planet in our solar system?",
    "What is the name of the galaxy we live in?",
    "Who is the author of 'To Kill a Mockingbird'?",
    "What is the capital of Canada?",
    "What is the main component of the sun?",
    "How many continents are there?",
    "What is the largest bone in the human body?",
    "Who developed the theory of relativity?",
    "What is the capital of Russia?",
    "What is the most spoken language in the world by number of native speakers?",
    "In which country are the pyramids of Giza?",
    "What is the chemical formula for table salt?",
    "Who was the first President of the United States?",
    "What is the largest ocean on Earth?",
    "What is the main function of the kidneys?",
    "Who wrote '1984'?",
    "What is the capital of Spain?",
    "What is the study of earthquakes called?",
    "How many planets are in our solar system?",
    "What is the capital of South Africa?",
    "What gas do plants absorb from the atmosphere?",
    "Who invented the light bulb?",
    "What is the largest mammal in the world?",
    "What is the capital of Italy?",
    "In what year did the American Civil War end?",
    "What element is a diamond made of?",
    "Who is known as the father of the computer?",
    "What is the capital of Germany?",
    "What is the most common blood type in humans?",
    "Who wrote 'The Great Gatsby'?",
    "What is the boiling point of water in Celsius?",
    "What is the capital of India?",
    "Who was a famous female pharaoh of ancient Egypt?",
    "What is the world's most populous country?",
    "What is the capital of Brazil?",
    "What is the main cause of tides?",
    "Who painted the ceiling of the Sistine Chapel?",
    "What is the capital of Argentina?",
    "What is the largest moon of Saturn?",
    "What is the study of fossils called?",
    "What is the main currency of the European Union?",
    "Who wrote 'Pride and Prejudice'?",
    "What is the capital of Mexico?",
    "What is a group of lions called?",
    "In which U.S. state is the Grand Canyon located?",
    "What is the smallest country in the world?",
    "Who wrote 'The Catcher in the Rye'?",
    "What is the capital of South Korea?",
    "What is the chemical symbol for silver?",
    "What is the process of a liquid turning into a gas called?",
    "Who was the Greek god of the sea?",
    "What is the capital of Egypt?",
    "What is the main purpose of a plant's roots?",
    "What is the largest country by land area?",
    "What is the common name for sodium chloride?",
    "What is the capital of Thailand?",
    "Who invented the World Wide Web?",
    "What is the largest continent?",
    "What is the main function of red blood cells?",
    "What is the capital of Turkey?",
    "What is the study of insects called?",
    "Who wrote 'Don Quixote'?",
    "What is the capital of Sweden?",
    "What is the human body's largest organ?",
    "Who composed 'The Four Seasons'?",
    "What is the capital of Norway?",
    "What is the process of a solid turning directly into a gas called?",
    "What is the capital of Portugal?",
    "What was the name of the first man-made satellite to orbit Earth?",
    "What is the main religion in India?",
    "What is the capital of Greece?",
    "Who wrote the 'Communist Manifesto'?",
)

# Test prompts for text reranking (documents)
TEXT_RERANKING_DOCUMENTS = (
    "The capital of China is Beijing.",
    "Gravity is a force that attracts two bodies.",
    "Machine learning is a subset of artificial intelligence.",
    "William Shakespeare wrote 'Romeo and Juliet'.",
    "The chemical formula for water is H2O.",
    "Mount Everest is the highest mountain in the world.",
    "Photosynthesis is the process used by plants to convert light energy into chemical energy.",
    "World War II ended in 1945.",
    "Jupiter is the largest planet in our solar system.",
    "The currency of Japan is the Yen.",
    "Leonardo da Vinci painted the Mona Lisa.",
    "The capital of Japan is Tokyo.",
    "The mitochondrion is known as the powerhouse of the cell.",
    "The Titanic sank in the year 1912.",
    "The chemical symbol for gold is Au.",
    "J.K. Rowling wrote the Harry Potter series.",
    "The Antarctic Polar Desert is the largest desert in the world.",
    "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
    "The currency of the United Kingdom is the pound sterling.",
    "Neil Armstrong was the first person to walk on the moon.",
    "The main ingredient in guacamole is avocado.",
    "The first World War began in 1914.",
    "The capital of Australia is Canberra.",
    "Diamond is the hardest known natural material.",
    "Alexander Fleming discovered penicillin.",
    "The Nile River is considered the longest river in the world.",
    "The primary language spoken in Brazil is Portuguese.",
    "Vincent van Gogh painted 'Starry Night'.",
    "Mercury is the smallest planet in our solar system.",
    "The galaxy we live in is called the Milky Way.",
    "Harper Lee is the author of 'To Kill a Mockingbird'.",
    "The capital of Canada is Ottawa.",
    "The sun is primarily composed of hydrogen gas.",
    "There are seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.",
    "The femur, or thigh bone, is the largest bone in the human body.",
    "Albert Einstein developed the theory of relativity.",
    "The capital of Russia is Moscow.",
    "Mandarin Chinese is the language with the most native speakers.",
    "The pyramids of Giza are located in Egypt.",
    "The chemical formula for table salt is NaCl.",
    "George Washington was the first President of the United States.",
    "The Pacific Ocean is the largest and deepest of the world's oceans.",
    "The main function of the kidneys is to remove waste products and excess fluid from the body.",
    "George Orwell wrote the novel '1984'.",
    "The capital of Spain is Madrid.",
    "The study of earthquakes and seismic waves is called seismology.",
    "There are eight planets in our solar system.",
    "South Africa has three capital cities: Pretoria (executive), Bloemfontein (judicial), and Cape Town (legislative).",
    "Plants absorb carbon dioxide (CO2) from the atmosphere for photosynthesis.",
    "Thomas Edison is widely credited with inventing the first commercially practical incandescent light bulb.",
    "The blue whale is the largest mammal on Earth.",
    "The capital of Italy is Rome.",
    "The American Civil War ended in 1865.",
    "A diamond is a solid form of the element carbon.",
    "Charles Babbage is considered the 'father of the computer'.",
    "The capital of Germany is Berlin.",
    "O-positive is the most common blood type among humans.",
    "F. Scott Fitzgerald wrote 'The Great Gatsby'.",
    "The boiling point of water at standard atmospheric pressure is 100 degrees Celsius.",
    "The capital of India is New Delhi.",
    "Hatshepsut was one of the most powerful female pharaohs of ancient Egypt.",
    "As of 2023, India has surpassed China as the world's most populous country.",
    "The capital of Brazil is Brasília.",
    "Tides are primarily caused by the gravitational pull of the Moon.",
    "Michelangelo painted the ceiling of the Sistine Chapel.",
    "The capital of Argentina is Buenos Aires.",
    "Titan is the largest moon of Saturn.",
    "The study of fossils to understand the history of life on Earth is called paleontology.",
    "The Euro (€) is the official currency of 20 of the 27 member states of the European Union.",
    "Jane Austen wrote the novel 'Pride and Prejudice'.",
    "The capital of Mexico is Mexico City.",
    "A group of lions is called a pride.",
    "The Grand Canyon is located in the state of Arizona.",
    "Vatican City is the smallest independent state in the world by both area and population.",
    "J.D. Salinger wrote 'The Catcher in the Rye'.",
    "The capital of South Korea is Seoul.",
    "The chemical symbol for silver is Ag.",
    "The process where a liquid turns into a gas is called evaporation or vaporization.",
    "In Greek mythology, Poseidon is the god of the sea, earthquakes, and horses.",
    "The capital of Egypt is Cairo.",
    "The primary functions of a plant's roots are absorption of water and inorganic nutrients, and anchoring the plant body to the ground.",
    "Russia is the largest country in the world by land area.",
    "The common name for the chemical compound sodium chloride (NaCl) is salt.",
    "The capital of Thailand is Bangkok.",
    "Tim Berners-Lee, a British scientist, invented the World Wide Web in 1989.",
    "Asia is the largest continent by land area and population.",
    "The main function of red blood cells is to transport oxygen to the body's tissues in exchange for carbon dioxide.",
    "The capital of Turkey is Ankara.",
    "The scientific study of insects is called entomology.",
    "Miguel de Cervantes wrote the novel 'Don Quixote'.",
    "The capital of Sweden is Stockholm.",
    "The skin is the largest organ of the human body.",
    "Antonio Vivaldi, an Italian composer, wrote 'The Four Seasons'.",
    "The capital of Norway is Oslo.",
    "Sublimation is the transition of a substance directly from the solid to the gas state.",
    "The capital of Portugal is Lisbon.",
    "Sputnik 1, launched by the Soviet Union in 1957, was the first artificial Earth satellite.",
    "Hinduism is the most widely practiced religion in India.",
    "The capital of Greece is Athens.",
    "The 'Communist Manifesto' was written by Karl Marx and Friedrich Engels.",
)

TEXT_GENERATION_PROMPTS = (
    "Is the capital of China Beijing? Answer with Yes or No.",
    "Is the capital of France London? Answer with Yes or No.",
    "Is 2+2 equal to 4? Answer with Yes or No.",
    "Is water made of HCL? Answer with Yes or No.",
    "Is the Earth round? Answer with Yes or No.",
    "Is Python a programming language? Answer with Yes or No.",
    "Is the sun a star? Answer with Yes or No.",
    "Is 3+3 equal to 16? Answer with Yes or No.",
    "Is the capital of Japan Osaka? Answer with Yes or No.",
    "Is 5+5 equal to 55? Answer with Yes or No.",

    "Is the Amazon the longest river in the world? Answer with Yes or No.",
    "Is Mount Everest the highest mountain on Earth? Answer with Yes or No.",
    "Is H2O the chemical formula for water? Answer with Yes or No.",
    "Is 10 * 10 equal to 100? Answer with Yes or No.",
    "Was William Shakespeare a playwright? Answer with Yes or No.",
    "Is Leonardo da Vinci famous for painting the Mona Lisa? Answer with Yes or No.",
    "Is the Pacific Ocean the largest ocean on Earth? Answer with Yes or No.",
    "Is photosynthesis the process by which plants make food? Answer with Yes or No.",
    "Is gravity a force that attracts objects with mass? Answer with Yes or No.",
    "Is the speed of light faster than the speed of sound? Answer with Yes or No.",
    "Was the American Declaration of Independence signed in 1776? Answer with Yes or No.",
    "Is an octagon a polygon with eight sides? Answer with Yes or No.",
    "Is the boiling point of water at sea level 100 degrees Celsius? Answer with Yes or No.",
    "Is the currency of the United Kingdom the Pound Sterling? Answer with Yes or No.",
    "Is the human heart a muscle? Answer with Yes or No.",
    "Is Venus the second planet from the Sun? Answer with Yes or No.",
    "Is a decade a period of 10 years? Answer with Yes or No.",
    "Is Nelson Mandela a former president of South Africa? Answer with Yes or No.",
    "Is an atom the smallest unit of a chemical element? Answer with Yes or No.",
    "Is Rome the capital of Italy? Answer with Yes or No.",
    "Is 12 * 12 equal to 144? Answer with Yes or No.",
    "Is Spanish the official language of Mexico? Answer with Yes or No.",
    "Is Jupiter the largest planet in our solar system? Answer with Yes or No.",
    "Did World War II end in 1945? Answer with Yes or No.",
    "Is the Nile River located in Africa? Answer with Yes or No.",
    "Is a prime number a number greater than 1 with no positive divisors other than 1 and itself? Answer with Yes or No.",
    "Is the capital of Australia Canberra? Answer with Yes or No.",
    "Is diamond the hardest known natural material? Answer with Yes or No.",
    "Is the primary function of lungs breathing? Answer with Yes or No.",
    "Is a kilometer equal to 1000 meters? Answer with Yes or No.",
    "Is Albert Einstein known for the theory of relativity? Answer with Yes or No.",
    "Is the Sahara the largest hot desert in the world? Answer with Yes or No.",
    "Is oxygen essential for human respiration? Answer with Yes or No.",
    "Is a square a quadrilateral with four equal sides and four right angles? Answer with Yes or No.",
    "Is the capital of Russia Moscow? Answer with Yes or No.",
    "Is a violin a string instrument? Answer with Yes or No.",
    "Is an insect an animal with six legs? Answer with Yes or No.",
    "Is the currency of Japan the Yen? Answer with Yes or No.",
    "Is a triangle a polygon with three sides? Answer with Yes or No.",
    "Is a whale a mammal? Answer with Yes or No.",
    "Is the capital of Canada Ottawa? Answer with Yes or No.",
    "Is French an official language of Switzerland? Answer with Yes or No.",
    "Is helium lighter than air? Answer with Yes or No.",
    "Is chess considered a board game? Answer with Yes or No.",
    "Is 7 * 8 equal to 56? Answer with Yes or No.",
    "Is the moon larger than the sun? Answer with Yes or No.",
    "Is a penguin a mammal? Answer with Yes or No.",
    "Is the capital of the United States New York City? Answer with Yes or No.",
    "Is 7 a composite number? Answer with Yes or No.",
    "Was Christopher Columbus the first European to land in North America? Answer with Yes or No.",
    "Is a spider an insect? Answer with Yes or No.",
    "Is the freezing point of water 10 degrees Celsius? Answer with Yes or No.",
    "Is Mars the largest planet in the solar system? Answer with Yes or No.",
    "Is a year on Earth 360 days long? Answer with Yes or No.",
    "Is the capital of Brazil Rio de Janeiro? Answer with Yes or No.",
    "Is an apple a vegetable? Answer with Yes or No.",
    "Is 9 * 8 equal to 71? Answer with Yes or No.",
    "Is the human body composed of 90% water? Answer with Yes or No.",
    "Did the Titanic sink in the Pacific Ocean? Answer with Yes or No.",
    "Is a shark a mammal? Answer with Yes or No.",
    "Is gold a liquid at room temperature? Answer with Yes or No.",
    "Is the capital of India Mumbai? Answer with Yes or No.",
    "Is 25 / 5 equal to 4? Answer with Yes or No.",
    "Is a bat a bird? Answer with Yes or No.",
    "Was Vincent van Gogh a French artist? Answer with Yes or No.",
    "Is the main component of Earth's atmosphere oxygen? Answer with Yes or No.",
    "Is the capital of Australia Sydney? Answer with Yes or No.",
    "Is a tomato botanically a vegetable? Answer with Yes or No.",
    "Is 100 - 55 equal to 40? Answer with Yes or No.",
    "Is a turtle an amphibian? Answer with Yes or No.",
    "Is the Statue of Liberty located in Washington D.C.? Answer with Yes or No.",
    "Did World War I start in 1920? Answer with Yes or No.",
    "Is the currency of China the Dollar? Answer with Yes or No.",
    "Is the primary language of Brazil Spanish? Answer with Yes or No.",
    "Is a dog a reptile? Answer with Yes or No.",
    "Is 15 a prime number? Answer with Yes or No.",
    "Is the Eiffel Tower located in London? Answer with Yes or No.",
    "Is a mushroom a plant? Answer with Yes or No.",
    "Is Mercury the hottest planet in the solar system? Answer with Yes or No.",
    "Is Antarctica a country? Answer with Yes or No.",
    "Is 11 * 11 equal to 122? Answer with Yes or No.",
    "Is the capital of Spain Barcelona? Answer with Yes or No.",
    "Is sound faster than light? Answer with Yes or No.",
    "Is the sun a planet? Answer with Yes or No.",
    "Is a chicken a mammal? Answer with Yes or No.",
    "Is a century a period of 50 years? Answer with Yes or No.",
    "Is the capital of Egypt Alexandria? Answer with Yes or No.",
    "Is a square a type of circle? Answer with Yes or No.",
    "Is 50 + 50 equal to 200? Answer with Yes or No.",
)
